### PR TITLE
Feature/ping during demo

### PR DESCRIPTION
**Pull request by pawanrawal**
Trying to change streaming endpoint to RPC. That makes it easier to enable pings during demo.

TODO - Retry RPC to server until x mins and show appropriate status in status box.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/gru/22)

### CODE REVIEW

**Comment by ashwin95r** [comment]
*) On running the client and server, the error page doesn't show up when the server crashes. 
*) Also, when the server comes back up, the following logs show up : 
```
2016/07/06 04:49:39 Error: invalid argument while writing logs to file for Cand: Pawan Rawal
2016/07/06 04:49:39 Got ping before demo for Cand: Pawan Rawal
2016/07/06 04:49:44 Error: invalid argument while writing logs to file for Cand: Pawan Rawal
2016/07/06 04:49:44 Got ping before demo for Cand: Pawan Rawal
2016/07/06 04:49:49 Error: invalid argument while writing logs to file for Cand: Pawan Rawal
2016/07/06 04:49:49 Got ping before demo for Cand: Pawan Rawal
2016/07/06 04:49:54 Error: invalid argument while writing logs to file for Cand: Pawan Rawal
2016/07/06 04:49:54 Got ping before demo for Cand: Pawan Rawal
2016/07/06 04:49:59 Error: invalid argument while writing logs to file for Cand: Pawan Rawal
2016/07/06 04:49:59 Got ping before demo for Cand: Pawan Rawal
```

---

Review status: 0 of 5 files reviewed at latest revision, 5 unresolved discussions.

---

*[client/main.go, line 61 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/22#-KLySltmDt4XrVvFqIDI:-KLySltmDt4XrVvFqIDJ:-803675831) ([raw file](https://github.com/dgraph-io/gru/blob/31d0df498d1a918b53357768467e306e0555d124/client/main.go#L61)):*
> ```Go
> 	showingAns   bool
> 	startedPing  bool
> 	testEndCh    chan struct{}
> ```

Any reason that it is an empty struct? Could just be an integer or a string.

---

*[client/main.go, line 171 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/22#-KLyTu5V0jbaNq7vK3Z3:-KLyTu5V0jbaNq7vK3Z4:-370841355) ([raw file](https://github.com/dgraph-io/gru/blob/31d0df498d1a918b53357768467e306e0555d124/client/main.go#L171)):*
> ```Go
> 			select {
> 			case <-s.testEndCh:
> 				break L
> ```

Won't just a return be sufficient here? 

---

*[client/main.go, line 174 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/22#-KLyTX7hzAP8e7C3LlGC:-KLyTX7hzAP8e7C3LlGD:-1130471633) ([raw file](https://github.com/dgraph-io/gru/blob/31d0df498d1a918b53357768467e306e0555d124/client/main.go#L174)):*
> ```Go
> 			default:
> 				sendStatus()
> 			}
> ```

Would be better if the loop is structured like this so that there wont be a delay in consuming the testEndCh which would be checked only every 5 seconds now.
```
for {
 select {
  case <- s.testEndCh:
   .
   case <- ticker.C:
    sendStatus()

 }
}
```

---

*[client/main.go, line 423 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/22#-KLyUMD434v2iXPkHUeH:-KLyUMD434v2iXPkHUeI:-1495445972) ([raw file](https://github.com/dgraph-io/gru/blob/31d0df498d1a918b53357768467e306e0555d124/client/main.go#L423)):*
> ```Go
> 	defer termui.Close()
> 
> 	s.testEndCh = make(chan struct{}, 2)
> ```

Could be an int or a string.

---

*[client/render.go, line 245 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/22#-KLyUTxdjglabEzzElrA:-KLyUTxdjglabEzzElrB:160841994) ([raw file](https://github.com/dgraph-io/gru/blob/31d0df498d1a918b53357768467e306e0555d124/client/render.go#L245)):*
> ```Go
> 
> func showFinalPage(msg string) {
> 	s.testEndCh <- struct{}{}
> ```

Same as above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/22#-:-KLyWjzKP4YXjb7mw6Ig:-1183954908)*

**Comment by ashwin95r** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/22)*

**Comment by pawanrawal** [comment]
Checking these.

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[client/main.go, line 61 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/22#-KLySltmDt4XrVvFqIDI:-KLyZ8qmoRIm0LJ3LS9M:-12422528) ([raw file](https://github.com/dgraph-io/gru/blob/31d0df498d1a918b53357768467e306e0555d124/client/main.go#L61)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> Any reason that it is an empty struct? Could just be an integer or a string.
</details>
The thing is that the value doesn't matter hence kept it as empty struct. Took inspiration from here https://blog.golang.org/pipelines

---

*[client/main.go, line 171 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/22#-KLyTu5V0jbaNq7vK3Z3:-KLyZtlZU5mt6K13DGHp:-624748607) ([raw file](https://github.com/dgraph-io/gru/blob/31d0df498d1a918b53357768467e306e0555d124/client/main.go#L171)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> Won't just a return be sufficient here? 
</details>
Should be, they'd establish the same things.

---

*[client/main.go, line 174 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/22#-KLyTX7hzAP8e7C3LlGC:-KLy_AxOqwIA5fIjrHpt:-1206431433) ([raw file](https://github.com/dgraph-io/gru/blob/31d0df498d1a918b53357768467e306e0555d124/client/main.go#L174)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> Would be better if the loop is structured like this so that there wont be a delay in consuming the testEndCh which would be checked only every 5 seconds now.
> ```
> for {
>  select {
>   case <- s.testEndCh:
>    .
>    case <- ticker.C:
>     sendStatus()
> 
>  }
> }
> ```
> 
</details>
Good point, this makes sense.

---

*[client/main.go, line 423 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/22#-KLyUMD434v2iXPkHUeH:-KLy_HZO4WV4UORcs9PN:-1003433342) ([raw file](https://github.com/dgraph-io/gru/blob/31d0df498d1a918b53357768467e306e0555d124/client/main.go#L423)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> Could be an int or a string.
</details>
Same point as above. IMHO its better to pass an empty struct instead of a value like 1 or 2.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/22#-:-KLy_F9aw5vhLh59BBjC:273775436)*

**Comment by manishrjain** [comment]
I love this change. It deletes more code than it adds while simplifying the logic. These are the kind of PRs that I'm proud of. 

---

Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[client/main.go, line 61 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/22#-KLySltmDt4XrVvFqIDI:-KLyZDUzWu_0IlLU50a5:-529285947) ([raw file](https://github.com/dgraph-io/gru/blob/31d0df498d1a918b53357768467e306e0555d124/client/main.go#L61)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> Any reason that it is an empty struct? Could just be an integer or a string.
</details>
This is the first empty struct chan we're using in Dgraph. Nice work! Ashwin: https://blog.golang.org/pipelines

---

*[client/main.go, line 136 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/22#-KLyZTZwYGiqebQi7U2G:-KLyZTZwYGiqebQi7U2H:921770757) ([raw file](https://github.com/dgraph-io/gru/blob/31d0df498d1a918b53357768467e306e0555d124/client/main.go#L136)):*
> ```Go
> 			clear()
> 			showFinalPage(finalScore(s.currentQn.Totscore))
> 			return
> ```

if return else return

---

*[client/main.go, line 144 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/22#-KLyaFExQIP_RuS6nE3f:-KLyaFExQIP_RuS6nE3g:1030141787) ([raw file](https://github.com/dgraph-io/gru/blob/31d0df498d1a918b53357768467e306e0555d124/client/main.go#L144)):*
> ```Go
> 	}
> 
> 	if serverS.Status == "END" {
> ```

Having a variable name end with an upper case is a bit strange. Change the naming.

---

*[client/main.go, line 174 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/22#-KLyTX7hzAP8e7C3LlGC:-KLyaV5AxjW95LOp25qk:1051009635) ([raw file](https://github.com/dgraph-io/gru/blob/31d0df498d1a918b53357768467e306e0555d124/client/main.go#L174)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Good point, this makes sense.
</details>
Agree with Ashwin. An infinite for loop, with 2 multiple select cases is the idiomatic Go way.

---

*[client/main.go, line 423 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/22#-KLyUMD434v2iXPkHUeH:-KLyahrW1mJK4g0aZfUJ:-1711597669) ([raw file](https://github.com/dgraph-io/gru/blob/31d0df498d1a918b53357768467e306e0555d124/client/main.go#L423)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Same point as above. IMHO its better to pass an empty struct instead of a value like 1 or 2.
</details>
Agree with Pawan. Empty struct channels have a meaning in Go.

Pawan: Just double check with the Go book on the best implementation using empty struct channels. I haven't used them much.

---

*[server/main.go, line 541 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/22#-KLybAHYFmtrxqoqbeWC:-KLybAHYFmtrxqoqbeWD:900937125) ([raw file](https://github.com/dgraph-io/gru/blob/31d0df498d1a918b53357768467e306e0555d124/server/main.go#L541)):*
> ```Go
> 	if c.testStart.IsZero() {
> 		demoTimeLeft := timeLeft(c.demoStart)
> 		if demoTimeLeft < 0 {
> ```

Looks like if demoTimeLeft > 0 would result in a shorter block, so do that condition first. In general, any cond which results in shorter block should go first.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/22#-:-KLybLrdGrMmDbVbtsPo:-632974147)*

**Comment by pawanrawal** [comment]
Will be fixing those bugs in a separate PR Ashwin.

---

Review status: 3 of 5 files reviewed at latest revision, 9 unresolved discussions.

---

*[client/main.go, line 136 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/22#-KLyZTZwYGiqebQi7U2G:-KLyepxJFmh_J54ukak3:-1291445927) ([raw file](https://github.com/dgraph-io/gru/blob/31d0df498d1a918b53357768467e306e0555d124/client/main.go#L136)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> if return else return
</details>
Shit, realized that `go lint` warns about this. So, i am going to use it now until I start seeing this.

---

*[client/main.go, line 144 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/22#-KLyaFExQIP_RuS6nE3f:-KLyfX0JmABGHuSWS9-j:1043863787) ([raw file](https://github.com/dgraph-io/gru/blob/31d0df498d1a918b53357768467e306e0555d124/client/main.go#L144)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Having a variable name end with an upper case is a bit strange. Change the naming.
</details>
Changed it to a const and using that everywhere.

---

*[client/main.go, line 174 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/22#-KLyTX7hzAP8e7C3LlGC:-KLyfbBZLEGHcNWkmfsi:-499146009) ([raw file](https://github.com/dgraph-io/gru/blob/31d0df498d1a918b53357768467e306e0555d124/client/main.go#L174)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Agree with Ashwin. An infinite for loop, with 2 multiple select cases is the idiomatic Go way.
</details>
Done.

---

*[client/main.go, line 423 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/22#-KLyUMD434v2iXPkHUeH:-KLygPFpR3dS_p0cgPAa:1859043103) ([raw file](https://github.com/dgraph-io/gru/blob/31d0df498d1a918b53357768467e306e0555d124/client/main.go#L423)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Agree with Pawan. Empty struct channels have a meaning in Go.
> 
> Pawan: Just double check with the Go book on the best implementation using empty struct channels. I haven't used them much.
</details>
They use it in a pretty similar manner.

---

*[client/render.go, line 245 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/22#-KLyUTxdjglabEzzElrA:-KLyigrylPd-FnfYOWlJ:-499146009) ([raw file](https://github.com/dgraph-io/gru/blob/31d0df498d1a918b53357768467e306e0555d124/client/render.go#L245)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> Same as above.
</details>
Done.

---

*[server/main.go, line 541 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/22#-KLybAHYFmtrxqoqbeWC:-KLylFp51S-oP_POubWZ:-499146009) ([raw file](https://github.com/dgraph-io/gru/blob/31d0df498d1a918b53357768467e306e0555d124/server/main.go#L541)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Looks like if demoTimeLeft > 0 would result in a shorter block, so do that condition first. In general, any cond which results in shorter block should go first.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/22#-:-KLyiYKArO-bdtCf8zcS:1521919996)*

**Comment by ashwin95r** [comment]
Sounds good. :lgtm:

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/22#-:-KLymjV63t3vnUkGPMao:-356004680)*

**Comment by pawanrawal** [comment]
Merged.

**Pull request closed without merging**
