### PR TITLE
Feature/ratelimit

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/gru/29)

### CODE REVIEW

**Comment by manishrjain** [comment]
Nice work! Clean and elegant solution.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[server/main.go, line 830 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/29#-KMSogocVUpdUqZIveNj:-KMSogodRc8KGn7W6O1s:1176139438) ([raw file](https://github.com/dgraph-io/gru/blob/019fdbc575005db40b6bc0a88ebf1fa661d4cb99/server/main.go#L830)):*
> ```Go
> 
> 	for t := range rateTicker.C {
> 		throttle <- t
> ```

So, I think things might accumulate in the rateTicker here. We need a way to throw away a tick if we can't immediately add it to throttle. Something like:

switch {
  case throttle <- t:
    break
  case default:
    break
}

Now the loop would try adding and just skip if it can't add. So, there's no accummulation.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/29#-:-KMSpXgBTIDJ4E-dBjcQ:-1921910363)*

**Comment by ashwin95r** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[server/main.go, line 830 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/29#-KMSogocVUpdUqZIveNj:-KMSrHfS754o3nlsBl84:573487075) ([raw file](https://github.com/dgraph-io/gru/blob/019fdbc575005db40b6bc0a88ebf1fa661d4cb99/server/main.go#L830)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> So, I think things might accumulate in the rateTicker here. We need a way to throw away a tick if we can't immediately add it to throttle. Something like:
> 
> switch {
>   case throttle <- t:
>     break
>   case default:
>     break
> }
> 
> Now the loop would try adding and just skip if it can't add. So, there's no accummulation.
</details>
Yeah. Good point. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/29)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/29#-:-KMSsaXLsojd5MlNfzP2:1417088721)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
