### PR TITLE
Feature/tls

### PR DESCRIPTION
**Pull request by pawanrawal**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/gru/20)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[client/main.go, line 30 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/20#-KLoUOLiiFy4ueGObjR5:-KLoUOLj6TzRgRIg68lc:1034359495) ([raw file](https://github.com/dgraph-io/gru/blob/7dd7659ab48e6840bf564ee513ea37b24bfbb2bf/client/main.go#L30)):*
> ```Go
> 	token              = flag.String("token", "testtoken", "Authentication token")
> 	address            = flag.String("address", "52.8.225.224:8142", "Address of the server")
> 	tls                = flag.Bool("tls", false, "Connection uses TLS if true, else plain TCP")
> ```

Is this false for testing purposes? If this is false, gru server won't respond right?

---

*[client/main.go, line 31 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/20#-KLoUK1cCBnqmrbpP6Xj:-KLoUK1cCBnqmrbpP6Xk:1639737670) ([raw file](https://github.com/dgraph-io/gru/blob/7dd7659ab48e6840bf564ee513ea37b24bfbb2bf/client/main.go#L31)):*
> ```Go
> 	address            = flag.String("address", "52.8.225.224:8142", "Address of the server")
> 	tls                = flag.Bool("tls", false, "Connection uses TLS if true, else plain TCP")
> 	serverHostOverride = flag.String("server_host_override", "gru.dgraph.io",
> ```

What is this flag for? Shouldn't this be the address?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/20)*

**Comment by pawanrawal** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[client/main.go, line 30 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/20#-KLoUOLiiFy4ueGObjR5:-KLoWmTmqoxaS-hEXkgD:-1474933456) ([raw file](https://github.com/dgraph-io/gru/blob/7dd7659ab48e6840bf564ee513ea37b24bfbb2bf/client/main.go#L30)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Is this false for testing purposes? If this is false, gru server won't respond right?
</details>
Yes, if this is false a gru server which has `tls=true` doesn't authenticate.  Though if a server is initialized for testing with `tls=false`, then the client can connect to it with `tls=false`.

---

*[client/main.go, line 31 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/20#-KLoUK1cCBnqmrbpP6Xj:-KLoYJatmwhLKO7Sipbe:-2092124054) ([raw file](https://github.com/dgraph-io/gru/blob/7dd7659ab48e6840bf564ee513ea37b24bfbb2bf/client/main.go#L31)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> What is this flag for? Shouldn't this be the address?
</details>
Hmm, this is used to verify the server cert. The cert is issued for `gru.dgraph.io`. Connection is made by dialing the actual address.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/20)*

**Comment by manishrjain** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[client/main.go, line 31 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/20#-KLoUK1cCBnqmrbpP6Xj:-KLo_YVtPVLyF-zC7yJl:1771375094) ([raw file](https://github.com/dgraph-io/gru/blob/7dd7659ab48e6840bf564ee513ea37b24bfbb2bf/client/main.go#L31)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Hmm, this is used to verify the server cert. The cert is issued for `gru.dgraph.io`. Connection is made by dialing the actual address.
</details>
Why not set address to gru.dgraph.io, and use that same address for checking the certs?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/20)*

**Comment by pawanrawal** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[client/main.go, line 31 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/20#-KLoUK1cCBnqmrbpP6Xj:-KLogC94lzHgCWq23tvG:-378436102) ([raw file](https://github.com/dgraph-io/gru/blob/7dd7659ab48e6840bf564ee513ea37b24bfbb2bf/client/main.go#L31)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Why not set address to gru.dgraph.io, and use that same address for checking the certs?
</details>
That can be done I suppose. Though it would mean we can run the server on port 80 only.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/20)*

**Comment by manishrjain** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[client/main.go, line 31 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/20#-KLoUK1cCBnqmrbpP6Xj:-KLogg2mxzSrkOywxMUG:-1415200237) ([raw file](https://github.com/dgraph-io/gru/blob/7dd7659ab48e6840bf564ee513ea37b24bfbb2bf/client/main.go#L31)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> That can be done I suppose. Though it would mean we can run the server on port 80 only.
</details>
Well, gru should always be running on 443 for TLS.

But, if you've set the address to IP:PORT, then you can just strip the part after ":PORT" to get the server host, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/20)*

**Comment by pawanrawal** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[client/main.go, line 31 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/20#-KLoUK1cCBnqmrbpP6Xj:-KLooawZ1w3YprdcoNW4:-530205350) ([raw file](https://github.com/dgraph-io/gru/blob/7dd7659ab48e6840bf564ee513ea37b24bfbb2bf/client/main.go#L31)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Well, gru should always be running on 443 for TLS.
> 
> But, if you've set the address to IP:PORT, then you can just strip the part after ":PORT" to get the server host, right?
</details>
Right, made the changes.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/20)*

**Comment by manishrjain** [comment]
Set TLS to true. Other than that, LGTM. :lgtm: 

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/20#-:-KLosjpk72xESk-aIzAm:-1098546783)*

**Comment by manishrjain** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/20#-:-KLouWEyZ667SkYBlL-i:1417088721)*

**Comment by pawanrawal** [comment]
Merged.

**Pull request closed without merging**
