### PR TITLE
Enable periodic reading of candidate files

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/gru/14)

### CODE REVIEW

**Comment by pawanrawal** [comment]
What would happen if a candidate with token `abc` is taking the test(has `c.questions` populated) and you add information for another candidate to the file. Now when the `candInfo` file is read again, what happens to the questions of the candidate taking the test?

Instead of testing this manually I would suggest writing a test case to check this. Read cand info from a candidate file. Then add questions for him. Do a get question. Now open the candidate file and append another token. Call your method to reread the cand file. After this read two things should happen.
1. New token should have been added to cmap.
2. State of the user who is taking the test shouldn't be changed.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[server/main.go, line 91 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/14#-KLdYAFWTy8DpNGWeI4X:-KLdYAFWTy8DpNGWeI4Y:-2010879998) ([raw file](https://github.com/dgraph-io/gru/blob/9ebecbf184b7cac9a6fb217a86258b76f71f5065/server/main.go#L91)):*
> ```Go
> 	mapLock.Lock()
> 	defer mapLock.Unlock()
> 	c, ok := cmap[token]
> ```

Maybe you don't need `ok`. If map doesn't contain a Candidate for the token, `c` would be `nil`.

---

*[server/main.go, line 723 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/14#-KLdYVHGnAD_24EYyb5z:-KLdYVHHDBIF3hTMgGwo:75716072) ([raw file](https://github.com/dgraph-io/gru/blob/9ebecbf184b7cac9a6fb217a86258b76f71f5065/server/main.go#L723)):*
> ```Go
> 	for {
> 		parseCandidateFile(file)
> 		time.Sleep(1 * time.Minute)
> ```

Maybe use `ticker`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/14#-:-KLdYaee7Z4EPvuWEAMi:-2003390013)*

**Comment by ashwin95r** [comment]
Good point, new candidate object shouldn't be created everytime. Addressed that.

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/main.go, line 91 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/14#-KLdYAFWTy8DpNGWeI4X:-KLduK_FdOEXFEkXoWVT:327650138) ([raw file](https://github.com/dgraph-io/gru/blob/9ebecbf184b7cac9a6fb217a86258b76f71f5065/server/main.go#L91)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Maybe you don't need `ok`. If map doesn't contain a Candidate for the token, `c` would be `nil`.
</details>
All the if contitions were checking for "ok" value, and I though it makes the code more readable. So, I think it's fine to have it this way

---

*[server/main.go, line 723 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/14#-KLdYVHGnAD_24EYyb5z:-KLdxYMuQqMJqB10SV44:-499146009) ([raw file](https://github.com/dgraph-io/gru/blob/9ebecbf184b7cac9a6fb217a86258b76f71f5065/server/main.go#L723)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Maybe use `ticker`.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/14#-:-KLdu9pK0Rngr3zWekjb:1231951839)*

**Comment by pawanrawal** [comment]
How about writing some tests?

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/14#-:-KLeeyKQEnlj06cPvCKM:-1918232130)*

**Comment by ashwin95r** [comment]
Yeah, will add it

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/14#-:-KLer43ZFaRVmSYWGCz7:-1421834420)*

**Comment by ashwin95r** [comment]
Since the global cmap is being used in parseCandidateFile, it is not possible to write test unless a lot of server code is rewritten, So we have to decide if we really need it now. Going through the logic of parseCandidateFile, we can see that the new candidate object is created only if we dont have the token already in the map. So, this should ensure the correctness.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/14#-:-KLoZLlVUErMpUR6gIpM:-108586722)*

**Comment by pawanrawal** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/main_test.go, line 452 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/gru/14#-KLogaN1LzoLqea2-J7z:-KLogaN1LzoLqea2-J8-:91420482) ([raw file](https://github.com/dgraph-io/gru/blob/48e5c0663b16672570a7514f47238afdc8ff6d64/server/main_test.go#L452)):*
> ```Go
> 	cmap = make(map[string]Candidate)
> 	questions, err := extractQuizInfo("demo_test.yaml")
> 	candFile, err := ioutil.TempFile("", "candFile")
> ```

I have a `cand_test.txt`, you could use that as I do in other tests.

---

*[server/main_test.go, line 488 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/gru/14#-KLohYkxpA6VzEis8GZX:-KLohYkxpA6VzEis8GZY:1155509779) ([raw file](https://github.com/dgraph-io/gru/blob/48e5c0663b16672570a7514f47238afdc8ff6d64/server/main_test.go#L488)):*
> ```Go
> 		log.Fatal("Candidate object updated on reading Candidate file")
> 	}
> ```

Also check cmap should have the new token and the candidate info.
Don't do `log.Fatal` , do `t.Fatal(err)`.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/14)*

**Comment by ashwin95r** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/main_test.go, line 452 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/gru/14#-KLogaN1LzoLqea2-J7z:-KLoi7cmNXyoKogUJDD1:355789946) ([raw file](https://github.com/dgraph-io/gru/blob/48e5c0663b16672570a7514f47238afdc8ff6d64/server/main_test.go#L452)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> I have a `cand_test.txt`, you could use that as I do in other tests.
</details>
This is a temporary file. should be okay I think.

---

*[server/main_test.go, line 488 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/gru/14#-KLohYkxpA6VzEis8GZX:-KLoj6O-jtfpMrDy8Axl:-499146009) ([raw file](https://github.com/dgraph-io/gru/blob/48e5c0663b16672570a7514f47238afdc8ff6d64/server/main_test.go#L488)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Also check cmap should have the new token and the candidate info.
> Don't do `log.Fatal` , do `t.Fatal(err)`.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/14)*

**Comment by pawanrawal** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/main.go, line 57 \[r5\]](https://reviewable.io:443/reviews/dgraph-io/gru/14#-KLooyjN6d-_mStZ_Ixz:-KLooyjN6d-_mStZ_Iy-:1454275273) ([raw file](https://github.com/dgraph-io/gru/blob/1a1d218bceaf5b4a7e18ec873d83406357bf648e/server/main.go#L57)):*
> ```Go
> 	// TODO - Check this number should be less than total number of demo
> 	// questions in the file.
> 	maxDemoQns = 3
> ```

Why change it back to 3.

---

*[server/main_test.go, line 452 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/gru/14#-KLogaN1LzoLqea2-J7z:-KLop-s3zOtIXGgmO260:1992094362) ([raw file](https://github.com/dgraph-io/gru/blob/48e5c0663b16672570a7514f47238afdc8ff6d64/server/main_test.go#L452)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> This is a temporary file. should be okay I think.
</details>
It should be okay for sure. Though you could have avoided 8-10 lines here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/14)*

**Comment by ashwin95r** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[server/main_test.go, line 452 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/gru/14#-KLogaN1LzoLqea2-J7z:-KLopowRC58q6J-fgir7:-898924015) ([raw file](https://github.com/dgraph-io/gru/blob/48e5c0663b16672570a7514f47238afdc8ff6d64/server/main_test.go#L452)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> It should be okay for sure. Though you could have avoided 8-10 lines here.
</details>
I didn't want to write to an existing file everytime the test is run and which is also used by other test functions

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/14)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r5, 1 of 1 files at r6.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/14#-:-KLos3XAZM2Uuljl5gtT:1417088721)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
