### PR TITLE
Add cancel method for context, refactoring

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/gru/27)

### CODE REVIEW

**Comment by manishrjain** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[client/main.go, line 115 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/gru/27#-KM3ClHqZw90ScwSHE_t:-KM3ClHqZw90ScwSHE_u:-633988946) ([raw file](https://github.com/dgraph-io/gru/blob/5d1939ed2c02167dc0bcec158920abcede7348f7/client/main.go#L115)):*
> ```Go
> 	try := 0
> 	ticker := time.NewTicker(TIMEOUT).C
> 	for err != nil {
> ```

Do an infinite for {} loop, and put all the GetQuestion logic inside.

---

*[client/main.go, line 122 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/gru/27#-KM3DkXUEG027f-1fzE2:-KM3DkXV8Pd_gwGsvwcD:-108009897) ([raw file](https://github.com/dgraph-io/gru/blob/5d1939ed2c02167dc0bcec158920abcede7348f7/client/main.go#L122)):*
> ```Go
> 			&interact.Req{Repeat: false, Sid: s.Id, Token: *token})
> 		cancel()
> 		<-ticker
> ```

What if the err was nil, would you still want to wait for a tick here?

Also, did you confirm that the previous behavior was in fact, wrong? So, if the server is down the retry loop would exit really quickly?

---

*[client/main.go, line 165 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/gru/27#-KM3E92IAqkTqoPQdD5S:-KM3E92IAqkTqoPQdD5T:-1361931113) ([raw file](https://github.com/dgraph-io/gru/blob/5d1939ed2c02167dc0bcec158920abcede7348f7/client/main.go#L165)):*
> ```Go
> 			showErrorPage()
> 			return
> 		}
> ```

if > numretry { showErrorPage() } else { statusNoConnection() }
return

I think you could even put the whole thing in one line.

---

*[client/main.go, line 304 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/gru/27#-KM3EK8iPlxbMZ50bGMa:-KM3EK8iPlxbMZ50bGMb:-1307496094) ([raw file](https://github.com/dgraph-io/gru/blob/5d1939ed2c02167dc0bcec158920abcede7348f7/client/main.go#L304)):*
> ```Go
> 		try := 0
> 		ticker := time.NewTicker(TIMEOUT).C
> 		for err != nil {
> ```

Again, don't do the calling twice. As I mentioned in my review, put the whole thing in an infinite for loop.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/27)*

**Comment by manishrjain** [comment]
Btw, this doesn't count as refactoring.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/27#-:-KM3FcFKB1G38MGNhVYy:1101499871)*

**Comment by ashwin95r** [comment]
Review status: 0 of 1 files reviewed at latest revision, 4 unresolved discussions.

---

*[client/main.go, line 115 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/gru/27#-KM3ClHqZw90ScwSHE_t:-KM3JlLR1x3VCBBEh_ky:-499146009) ([raw file](https://github.com/dgraph-io/gru/blob/5d1939ed2c02167dc0bcec158920abcede7348f7/client/main.go#L115)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Do an infinite for {} loop, and put all the GetQuestion logic inside.
</details>
Done.

---

*[client/main.go, line 122 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/gru/27#-KM3DkXUEG027f-1fzE2:-KM3HNj_6ZCt5cdJ2G5B:13217359) ([raw file](https://github.com/dgraph-io/gru/blob/5d1939ed2c02167dc0bcec158920abcede7348f7/client/main.go#L122)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> What if the err was nil, would you still want to wait for a tick here?
> 
> Also, did you confirm that the previous behavior was in fact, wrong? So, if the server is down the retry loop would exit really quickly?
</details>
Ah, Will check for the error before blocking on the ticker channel.

Yes, it does exit quickly if the server is down.

---

*[client/main.go, line 165 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/gru/27#-KM3E92IAqkTqoPQdD5S:-KM3KKeOzasML5_22b_L:-228302236) ([raw file](https://github.com/dgraph-io/gru/blob/5d1939ed2c02167dc0bcec158920abcede7348f7/client/main.go#L165)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> if > numretry { showErrorPage() } else { statusNoConnection() }
> return
> 
> I think you could even put the whole thing in one line.
</details>
Done. Gofmt makes it multi-line :D 

---

*[client/main.go, line 304 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/gru/27#-KM3EK8iPlxbMZ50bGMa:-KM3JkItCtv4kUgrKPbk:-499146009) ([raw file](https://github.com/dgraph-io/gru/blob/5d1939ed2c02167dc0bcec158920abcede7348f7/client/main.go#L304)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Again, don't do the calling twice. As I mentioned in my review, put the whole thing in an infinite for loop.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/27)*

**Comment by manishrjain** [comment]
Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[client/main.go, line 119 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/gru/27#-KM3tEwpnRhgxEq9wJ78:-KM3tEwpnRhgxEq9wJ79:-1190643387) ([raw file](https://github.com/dgraph-io/gru/blob/2cfbeed919310f4966aa0c94d59e081e0170e1a6/client/main.go#L119)):*
> ```Go
> 		cancel()
> 		try++
> 		if err == nil {
> ```

if err == nil {
  break
}

if try >= NUMRETRY {
  showErrorPage()
  return
}

statusNoConnection()
log....

---

*[client/main.go, line 309 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/gru/27#-KM3tZneg1jJTFcCbQif:-KM3tZneg1jJTFcCbQig:160841994) ([raw file](https://github.com/dgraph-io/gru/blob/2cfbeed919310f4966aa0c94d59e081e0170e1a6/client/main.go#L309)):*
> ```Go
> 			cancel()
> 			try++
> 			if err == nil {
> ```

Same as above.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/27)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[client/main.go, line 119 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/gru/27#-KM3tEwpnRhgxEq9wJ78:-KM3w9pmDXZbEFFYIHos:-499146009) ([raw file](https://github.com/dgraph-io/gru/blob/2cfbeed919310f4966aa0c94d59e081e0170e1a6/client/main.go#L119)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> if err == nil {
>   break
> }
> 
> if try >= NUMRETRY {
>   showErrorPage()
>   return
> }
> 
> statusNoConnection()
> log....
</details>
Done.

---

*[client/main.go, line 309 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/gru/27#-KM3tZneg1jJTFcCbQif:-KM3wAxGpQTllF9Hzksm:-499146009) ([raw file](https://github.com/dgraph-io/gru/blob/2cfbeed919310f4966aa0c94d59e081e0170e1a6/client/main.go#L309)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Same as above.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/27)*

**Comment by manishrjain** [comment]
:lgtm: Fix up the commit messages when squashing.

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/27#-:-KM3xZHH8nLCq7x8pyS4:-740733076)*

**Comment by ashwin95r** [comment]
Done. Merged.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/27#-:-KM3xn9C7d2g47YqGq9u:-478969303)*

**Comment by pawanrawal** [comment]
Merged.

**Pull request closed without merging**
