### PR TITLE
Don't log fatal after one try and write logs to a file on client side

### PR DESCRIPTION
**Pull request by pawanrawal**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/gru/10)

### CODE REVIEW

**Comment by pawanrawal** [comment]
We should do similar handling for sendAnswer too. Try a few times, if it doesn't work show him final box and ask him to send over the log file to us.

---

Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[client/main.go, line 86 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/10#-KLQ7qOYimGUctheeMh0:-KLQ7qOYimGUctheeMh1:219111661) ([raw file](https://github.com/dgraph-io/gru/blob/d3a33b3a4f27289d51c576205a2db04460fb19f0/client/main.go#L86)):*
> ```Go
> 		&interact.Req{Repeat: false, Sid: s.Id, Token: *token})
> 
> 	for err != nil {
> ```

We should probably have a limit on the number of tries here. If there isn't any response after a while from the server, we should display him the final screen box that we do if his token is invalid for e.g. We can ask him to contact us in that box.

Also did you test it out by say disconnecting the server for a sec and see if this works.

---

*[client/main.go, line 384 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/10#-KLQ8hnFOkZjgGNRDin0:-KLQ8hnG58M-GhKq-hsy:2071266423) ([raw file](https://github.com/dgraph-io/gru/blob/d3a33b3a4f27289d51c576205a2db04460fb19f0/client/main.go#L384)):*
> ```Go
> 	try := 0
> 	conn, err = grpc.Dial(*address, grpc.WithInsecure())
> 	for err != nil {
> ```

```
Does this work
for err != nil || try <10 {

}
```
If it does we can move the `log.Fatal`  outside the loop. Infact instead of `log.Fatal` we could again show the box with a error message.
The user won't have any visual indication during this period. So its better if we keep the sleep down to 1 second? If he can't connect in 10 seconds I am sure there is a problem at our end.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/10#-:-KLQAVsD6vN-7JoYjlb0:1341358464)*

**Comment by ashwin95r** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[client/main.go, line 86 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/10#-KLQ7qOYimGUctheeMh0:-KLQJ1CSVOPx-aCHv_pD:1962519380) ([raw file](https://github.com/dgraph-io/gru/blob/d3a33b3a4f27289d51c576205a2db04460fb19f0/client/main.go#L86)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> We should probably have a limit on the number of tries here. If there isn't any response after a while from the server, we should display him the final screen box that we do if his token is invalid for e.g. We can ask him to contact us in that box.
> 
> Also did you test it out by say disconnecting the server for a sec and see if this works.
</details>
The client doesn't crash if the server crashes, but if the stream is broken, the client has to re-establish it and not the server. We need it handle it separately. This is only for temporary network errors.

---

*[client/main.go, line 384 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/10#-KLQ8hnFOkZjgGNRDin0:-KLQBeTI5K-uwKAViA5x:717124365) ([raw file](https://github.com/dgraph-io/gru/blob/d3a33b3a4f27289d51c576205a2db04460fb19f0/client/main.go#L384)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> ```
> Does this work
> for err != nil || try <10 {
> 
> }
> ```
> If it does we can move the `log.Fatal`  outside the loop. Infact instead of `log.Fatal` we could again show the box with a error message.
> The user won't have any visual indication during this period. So its better if we keep the sleep down to 1 second? If he can't connect in 10 seconds I am sure there is a problem at our end.
> 
</details>
It should be an &&.  Sure, we can show a screen with some info, can you create a new screen to take care of this?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/10)*

**Comment by pawanrawal** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[client/main.go, line 86 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/10#-KLQ7qOYimGUctheeMh0:-KLQOMYYKhANrq-qmIiA:-2048878968) ([raw file](https://github.com/dgraph-io/gru/blob/d3a33b3a4f27289d51c576205a2db04460fb19f0/client/main.go#L86)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> The client doesn't crash if the server crashes, but if the stream is broken, the client has to re-establish it and not the server. We need it handle it separately. This is only for temporary network errors.
</details>
Hmm, so there isn't any way we can test this? Also do we need this for `sendAnswer`?

---

*[client/main.go, line 384 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/10#-KLQ8hnFOkZjgGNRDin0:-KLQNlapMftfxI5mc5-l:1794003979) ([raw file](https://github.com/dgraph-io/gru/blob/d3a33b3a4f27289d51c576205a2db04460fb19f0/client/main.go#L384)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> It should be an &&.  Sure, we can show a screen with some info, can you create a new screen to take care of this?
</details>
It's already there, the new screen which is the instructions termui element below this. I will link it with this.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/10)*

**Comment by ashwin95r** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[client/main.go, line 86 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/10#-KLQ7qOYimGUctheeMh0:-KLQUI76kswbLrIyXrgK:1799546358) ([raw file](https://github.com/dgraph-io/gru/blob/d3a33b3a4f27289d51c576205a2db04460fb19f0/client/main.go#L86)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Hmm, so there isn't any way we can test this? Also do we need this for `sendAnswer`?
</details>
Yeah, we could have this for send answer too. 

---

*[client/main.go, line 384 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/10#-KLQ8hnFOkZjgGNRDin0:-KLQUf9UocDq_JRa89Jb:676958649) ([raw file](https://github.com/dgraph-io/gru/blob/d3a33b3a4f27289d51c576205a2db04460fb19f0/client/main.go#L384)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> It's already there, the new screen which is the instructions termui element below this. I will link it with this.
</details>
Okay

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/10)*

**Comment by pawanrawal** [comment]
Review status: 0 of 3 files reviewed at latest revision, 4 unresolved discussions.

---

*[client/main.go, line 384 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/10#-KLQ8hnFOkZjgGNRDin0:-KLVMkA8Ga-TgGUVIv9F:-499146009) ([raw file](https://github.com/dgraph-io/gru/blob/d3a33b3a4f27289d51c576205a2db04460fb19f0/client/main.go#L384)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> Okay
</details>
Done.

---

*[client/main.go, line 93 \[r6\]](https://reviewable.io:443/reviews/dgraph-io/gru/10#-KLVMEVSQ7KnY2i-AQzo:-KLVMEVSQ7KnY2i-AQzp:480351497) ([raw file](https://github.com/dgraph-io/gru/blob/43e200a59d4ed218534349853bbbbd3648d042e0/client/main.go#L93)):*
> ```Go
> 		try++
> 		if try > 10 {
> 			log.Fatal(err)
> ```

Change this to show Error page(). Also add this for sendAnswer()/other places we do log.Fatal. See if you can simulate and test it out. Though my guess is the ping would be trigerred first.

---

*[client/main.go, line 164 \[r6\]](https://reviewable.io:443/reviews/dgraph-io/gru/10#-KLVMPtYvh_-Mznr6iXG:-KLVMPtYvh_-Mznr6iXH:-553823591) ([raw file](https://github.com/dgraph-io/gru/blob/43e200a59d4ed218534349853bbbbd3648d042e0/client/main.go#L164)):*
> ```Go
> 				}
> 
> 				if count > 2 {
> ```

Maybe instead of having different number of retries at every place. Make this a constant and reuse it?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/10)*

**Comment by ashwin95r** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[client/main.go, line 93 \[r6\]](https://reviewable.io:443/reviews/dgraph-io/gru/10#-KLVMEVSQ7KnY2i-AQzo:-KLVVIkk5w3pSlm8eeSk:1537605425) ([raw file](https://github.com/dgraph-io/gru/blob/43e200a59d4ed218534349853bbbbd3648d042e0/client/main.go#L93)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Change this to show Error page(). Also add this for sendAnswer()/other places we do log.Fatal. See if you can simulate and test it out. Though my guess is the ping would be trigerred first.
</details>
Done. and yeah time based ping is more likely to be triggered

---

*[client/main.go, line 164 \[r6\]](https://reviewable.io:443/reviews/dgraph-io/gru/10#-KLVMPtYvh_-Mznr6iXG:-KLVVX-siMlT95MPSv7E:1396921049) ([raw file](https://github.com/dgraph-io/gru/blob/43e200a59d4ed218534349853bbbbd3648d042e0/client/main.go#L164)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Maybe instead of having different number of retries at every place. Make this a constant and reuse it?
</details>
This would be once every 5 seconds. So 2 would be good as we don't want to wait for more than 10 seconds. At other places we use time.Sleep

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/10)*

**Comment by pawanrawal** [comment]
Merged!

**Pull request closed without merging**
