### PR TITLE
Use gogo proto

### PR DESCRIPTION
**Pull request by ashwin95r**
Shift to gogo protobuf: https://github.com/gogo/protobuf

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/gru/31)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Also, update the command in `.proto` file to generate the `.pb.go` file. Do we need to vendor in this library?

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/31#-:-KNAuEm6wYD1yadn88QD:-229062138)*

**Comment by ashwin95r** [comment]
Updated the comments. No, we dont have to. Just need to do `go get github.com/gogo/protobuf/protoc-gen-gofast` before compiling the proto files.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/31#-:-KNAvp8lPOGIaPQbOdE2:-1685016226)*

**Comment by pawanrawal** [comment]
Do one more thing add this as a comment. That before running the command, we need to `go get` library. Imagine someone new to the project, they wouldn't know about this. Otherwise :lgtm: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/31#-:-KNAx6ZjKcfRWctb2EkB:1443212620)*

**Comment by ashwin95r** [comment]
Merged.

**Pull request closed without merging**
