### PR TITLE
Enable demo without token

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/gru/12)

### CODE REVIEW

**Comment by pawanrawal** [comment]
The demo instructions screen doesn't appear. Thats because the state() function returns DEMO_STARTED. Can you figure how it would work for this case?

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[client/main.go, line 384 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/12#-KLV6e98ci7rPkl0_LK1:-KLV6e98ci7rPkl0_LK2:2028816937) ([raw file](https://github.com/dgraph-io/gru/blob/6134b76eaef7bf06705beaa2c6a814885a3da900/client/main.go#L384)):*
> ```Go
> 	flag.Parse()
> 
> 	if *token == "testtoken" {
> ```

Maybe just make the default value as empty and then check for token being empty.

---

*[server/main.go, line 59 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/12#-KLV3FVifXHprr69IuaQ:-KLV3FVifXHprr69IuaR:-1118887599) ([raw file](https://github.com/dgraph-io/gru/blob/6134b76eaef7bf06705beaa2c6a814885a3da900/server/main.go#L59)):*
> ```Go
> 	// TODO - Check this number should be less than total number of demo
> 	// questions in the file.
> 	maxDemoQns = 10
> ```

In the check for the yaml file, also check that we should have 10 demo questions else `log.Fatal`.

---

*[server/main.go, line 209 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/12#-KLV68fsabPCjsdrOxx-:-KLV68ftdmCcvpSDYUZ3:65254593) ([raw file](https://github.com/dgraph-io/gru/blob/6134b76eaef7bf06705beaa2c6a814885a3da900/server/main.go#L209)):*
> ```Go
> 		}
> 	}
> 	return que
> ```

You would probably want to return only the first 10 demo questions. Or else he would see the test screen after the demo and get demo questions within the test screen. We might also want to have a different screen after they finish their demo incase they had a dummy token.

---

*[server/main.go, line 213 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/12#-KLV8FbPY7-Z25p3hKtl:-KLV8FbPY7-Z25p3hKtm:-1762999519) ([raw file](https://github.com/dgraph-io/gru/blob/6134b76eaef7bf06705beaa2c6a814885a3da900/server/main.go#L213)):*
> ```Go
> 
> func demoCandInfo(token string) Candidate {
> 	// This indicates candidate info exists in memory and the client could
> ```

Remove this, doesn't make sense here.

---

*[server/main.go, line 215 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/12#-KLV5eKVNgSiyty1t6YN:-KLV5eKVNgSiyty1t6YO:-1586142548) ([raw file](https://github.com/dgraph-io/gru/blob/6134b76eaef7bf06705beaa2c6a814885a3da900/server/main.go#L215)):*
> ```Go
> 	// This indicates candidate info exists in memory and the client could
> 	// have crashed.
> 	var c Candidate
> ```

Hmm, shouldn't you be checking if the candidate exists in the map first. Would this mean that you create a new Candidate on every call (GetQuestion,SendAnswer)?

---

*[server/main.go, line 220 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/12#-KLV6RnBU0uyK7ME2OBq:-KLV6RnCsSgvC85_jq6y:1949916062) ([raw file](https://github.com/dgraph-io/gru/blob/6134b76eaef7bf06705beaa2c6a814885a3da900/server/main.go#L220)):*
> ```Go
> 	c.validity = time.Now().Add(time.Duration(100 * time.Hour))
> 	c.testStart = time.Now()
> 	c.demoTaken = false
> ```

Not needed, its the default value.

---

*[server/main.go, line 221 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/12#-KLV6U0ECAzE8EZ2EfOn:-KLV6U0ECAzE8EZ2EfOo:-1698914169) ([raw file](https://github.com/dgraph-io/gru/blob/6134b76eaef7bf06705beaa2c6a814885a3da900/server/main.go#L221)):*
> ```Go
> 	c.testStart = time.Now()
> 	c.demoTaken = false
> 	c.score = 0
> ```

Not needed.

---

*[server/main.go, line 233 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/12#-KLV86EYRSUO_Jszff32:-KLV86EYRSUO_Jszff33:1370951876) ([raw file](https://github.com/dgraph-io/gru/blob/6134b76eaef7bf06705beaa2c6a814885a3da900/server/main.go#L233)):*
> ```Go
> 		c.logFile = f
> 		c.questions = onlyDemoQuestions()
> 		cmap[token] = c
> ```

You don't need this and the return below because you are already doing it outside this block.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/12#-:-KLV8rVEzbtQMcyR3xIP:1285923428)*

**Comment by ashwin95r** [comment]
Review status: 0 of 2 files reviewed at latest revision, 8 unresolved discussions.

---

*[client/main.go, line 384 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/12#-KLV6e98ci7rPkl0_LK1:-KLVCTXgHWxxNJPywQ6I:-1558075861) ([raw file](https://github.com/dgraph-io/gru/blob/6134b76eaef7bf06705beaa2c6a814885a3da900/client/main.go#L384)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Maybe just make the default value as empty and then check for token being empty.
</details>
Doesn't make a difference

---

*[server/main.go, line 59 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/12#-KLV3FVifXHprr69IuaQ:-KLVCDml35V6rSGLeOW4:-499146009) ([raw file](https://github.com/dgraph-io/gru/blob/6134b76eaef7bf06705beaa2c6a814885a3da900/server/main.go#L59)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> In the check for the yaml file, also check that we should have 10 demo questions else `log.Fatal`.
</details>
Done.

---

*[server/main.go, line 209 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/12#-KLV68fsabPCjsdrOxx-:-KLVCGV3PJxhaXZQJwTd:595322736) ([raw file](https://github.com/dgraph-io/gru/blob/6134b76eaef7bf06705beaa2c6a814885a3da900/server/main.go#L209)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> You would probably want to return only the first 10 demo questions. Or else he would see the test screen after the demo and get demo questions within the test screen. We might also want to have a different screen after they finish their demo incase they had a dummy token.
</details>
True, we could have a different end screen. Can you add an appropriate screen?

---

*[server/main.go, line 213 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/12#-KLV8FbPY7-Z25p3hKtl:-KLVAoGtF8O6ZPNl7TZW:-499146009) ([raw file](https://github.com/dgraph-io/gru/blob/6134b76eaef7bf06705beaa2c6a814885a3da900/server/main.go#L213)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Remove this, doesn't make sense here.
</details>
Done.

---

*[server/main.go, line 215 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/12#-KLV5eKVNgSiyty1t6YN:-KLVAMBEW_qz3cs0MUhT:-2027982887) ([raw file](https://github.com/dgraph-io/gru/blob/6134b76eaef7bf06705beaa2c6a814885a3da900/server/main.go#L215)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Hmm, shouldn't you be checking if the candidate exists in the map first. Would this mean that you create a new Candidate on every call (GetQuestion,SendAnswer)?
</details>
No, everytime a new client connects it'll have a new token

---

*[server/main.go, line 220 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/12#-KLV6RnBU0uyK7ME2OBq:-KLVASQYbEnd4hySPnNE:-499146009) ([raw file](https://github.com/dgraph-io/gru/blob/6134b76eaef7bf06705beaa2c6a814885a3da900/server/main.go#L220)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Not needed, its the default value.
</details>
Done.

---

*[server/main.go, line 221 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/12#-KLV6U0ECAzE8EZ2EfOn:-KLVASvYRAaYVsR64f_v:-499146009) ([raw file](https://github.com/dgraph-io/gru/blob/6134b76eaef7bf06705beaa2c6a814885a3da900/server/main.go#L221)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Not needed.
</details>
Done.

---

*[server/main.go, line 233 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/12#-KLV86EYRSUO_Jszff32:-KLVAVq0_j8Iki6RKmIQ:-499146009) ([raw file](https://github.com/dgraph-io/gru/blob/6134b76eaef7bf06705beaa2c6a814885a3da900/server/main.go#L233)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> You don't need this and the return below because you are already doing it outside this block.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/12)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/12#-:-KLVHG6FGU5FO7tWlXi8:1417088721)*

**Comment by pawanrawal** [comment]
Merged.

**Pull request closed without merging**
