### PR TITLE
Allow the options to shuffle.

### LINKED ISSUE #30: Shuffle the options for every question
The objective here is to randomize the order of options for a question before sending it to a candidate. We already randomize the order of questions. Something similar for answer options should work.

### PR DESCRIPTION
**Pull request by mohitranka**
Fixes #30.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/gru/33)

### CODE REVIEW

**Comment by mohitranka** [comment]
@dgraph-io/team As I am fairly new to golang, please be extra thorough in your review. If something feels beyond my reach, I'd let you know.

**Comment by manishrjain** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[gruserver/main.go, line 270 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/33#-KNJTz6JOZGm-OYvEQSg:-KNJTz6JOZGm-OYvEQSh:1632110147) ([raw file](https://github.com/dgraph-io/gru/blob/65cbff9bc4593fcad362c7d4e93e2a0f1e3765c1/gruserver/main.go#L270)):*
> ```Go
> }
> 
> func shuffleQues(qns []Question) {
> ```

Please don't use abbreviations which are not common. In this case, either call it shuffleQns or shuffleQuestions

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/33)*

**Comment by mohitranka** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[gruserver/main.go, line 270 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/33#-KNJTz6JOZGm-OYvEQSg:-KNJYlDp-kc7aXolP0pf:1915108299) ([raw file](https://github.com/dgraph-io/gru/blob/65cbff9bc4593fcad362c7d4e93e2a0f1e3765c1/gruserver/main.go#L270)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Please don't use abbreviations which are not common. In this case, either call it shuffleQns or shuffleQuestions
</details>
FWIW google.com finds "ques ans" is more common than "qns ans" (http://www.awesomescreenshot.com/image/1419188/9923ef0f6c64865c7fdf8174ce41a6e7).

I will change it to "shuffleQuestions" though.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/33)*

**Comment by manishrjain** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[gruserver/main.go, line 270 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/33#-KNJTz6JOZGm-OYvEQSg:-KNJ_eIAlg5GgJXPz779:-1520556908) ([raw file](https://github.com/dgraph-io/gru/blob/65cbff9bc4593fcad362c7d4e93e2a0f1e3765c1/gruserver/main.go#L270)):*
<details><summary><i>Previously, mohitranka (Mohit Ranka) wrote…</i></summary>
> FWIW google.com finds "ques ans" is more common than "qns ans" (http://www.awesomescreenshot.com/image/1419188/9923ef0f6c64865c7fdf8174ce41a6e7).
> 
> I will change it to "shuffleQuestions" though.
</details>
Good point. Yup, shuffleQuestions works.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/33)*

**Comment by mohitranka** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[gruserver/main.go, line 270 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/33#-KNJTz6JOZGm-OYvEQSg:-KNJaVLzWob0tlIQsp-o:-499146009) ([raw file](https://github.com/dgraph-io/gru/blob/65cbff9bc4593fcad362c7d4e93e2a0f1e3765c1/gruserver/main.go#L270)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Good point. Yup, shuffleQuestions works.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/33)*

**Comment by pawanrawal** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[gruserver/main_test.go, line 566 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/gru/33#-KNLvo0-vP0YpwYD9BO1:-KNLvo0-vP0YpwYD9BO2:1042874637) ([raw file](https://github.com/dgraph-io/gru/blob/8325d0e8af7e7d2eacb06a4dcec9ed70d7540074/gruserver/main_test.go#L566)):*
> ```Go
> 		options = append(options, a)
> 	}
> 	oldOptions := make([]*interact.Answer, len(options))
> ```

`copy(oldOptions, options)`?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/33)*

**Comment by mohitranka** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[gruserver/main_test.go, line 566 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/gru/33#-KNLvo0-vP0YpwYD9BO1:-KNTIzgJACl0h6APenfu:-499146009) ([raw file](https://github.com/dgraph-io/gru/blob/8325d0e8af7e7d2eacb06a4dcec9ed70d7540074/gruserver/main_test.go#L566)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> `copy(oldOptions, options)`?
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/33)*

**Comment by mohitranka** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[gruserver/main_test.go, line 566 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/gru/33#-KNLvo0-vP0YpwYD9BO1:-KNTJ0zgyCfBBQ0-Zyo8:-200060196) ([raw file](https://github.com/dgraph-io/gru/blob/8325d0e8af7e7d2eacb06a4dcec9ed70d7540074/gruserver/main_test.go#L566)):*
<details><summary><i>Previously, mohitranka (Mohit Ranka) wrote…</i></summary>
> Done.
</details>
reflect.DeepEqual is not enough test for shuffle. Apart from this, a shallowEqual Must be same.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/33)*

**Comment by mohitranka** [comment]
Review status: 0 of 2 files reviewed at latest revision, 2 unresolved discussions.

---

*[gruserver/main_test.go, line 566 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/gru/33#-KNLvo0-vP0YpwYD9BO1:-KNTUtooDeCJirqgWsfY:-499146009) ([raw file](https://github.com/dgraph-io/gru/blob/8325d0e8af7e7d2eacb06a4dcec9ed70d7540074/gruserver/main_test.go#L566)):*
<details><summary><i>Previously, mohitranka (Mohit Ranka) wrote…</i></summary>
> reflect.DeepEqual is not enough test for shuffle. Apart from this, a shallowEqual Must be same.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/33)*

**Comment by pawanrawal** [comment]
Btw PR's should be assigned to just one person and not the whole team. You can assign them to me in the future. :lgtm: apart from a couple of things I mentioned.

---

Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[gruserver/main_test.go, line 566 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/gru/33#-KNLvo0-vP0YpwYD9BO1:-KNUxr13uGjD-u9Bsx2t:807670556) ([raw file](https://github.com/dgraph-io/gru/blob/8325d0e8af7e7d2eacb06a4dcec9ed70d7540074/gruserver/main_test.go#L566)):*
<details><summary><i>Previously, mohitranka (Mohit Ranka) wrote…</i></summary>
> Done.
</details>
Good point.

---

*[gruserver/main_test.go, line 582 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/gru/33#-KNUxPmIBm97SlIcOLgo:-KNUxPmIBm97SlIcOLgp:-1343610673) ([raw file](https://github.com/dgraph-io/gru/blob/52427d46648f6ad3fd0daa1db2d1913bb674d3d9/gruserver/main_test.go#L582)):*
> ```Go
> 
> func areOptionsEqual(x, y []*interact.Answer) bool {
> 	//http://stackoverflow.com/a/36000696
> ```

A space between `//` and `http` please.

---

*[gruserver/main_test.go, line 588 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/gru/33#-KNUxYT4hVmZ4lQEn-h5:-KNUxYT5weCgre2KPQzW:1639268841) ([raw file](https://github.com/dgraph-io/gru/blob/52427d46648f6ad3fd0daa1db2d1913bb674d3d9/gruserver/main_test.go#L588)):*
> ```Go
> 	// create a map of string -> int
> 	diff := make(map[*interact.Answer]int, len(x))
> 	for _, _x := range x {
> ```

Could we please change _x and _y, never seen variables named like that.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/33#-:-KNUy3kSLaSEpkDX9Pbc:-1713269136)*

**Comment by mohitranka** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[gruserver/main_test.go, line 588 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/gru/33#-KNUxYT4hVmZ4lQEn-h5:-KNVlYkCTfT2SdfLqrB_:-499146009) ([raw file](https://github.com/dgraph-io/gru/blob/52427d46648f6ad3fd0daa1db2d1913bb674d3d9/gruserver/main_test.go#L588)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Could we please change _x and _y, never seen variables named like that.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/33)*

**Comment by mohitranka** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[gruserver/main_test.go, line 582 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/gru/33#-KNUxPmIBm97SlIcOLgo:-KNVlccu5pjBqFxWsmnn:-499146009) ([raw file](https://github.com/dgraph-io/gru/blob/52427d46648f6ad3fd0daa1db2d1913bb674d3d9/gruserver/main_test.go#L582)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> A space between `//` and `http` please.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/33)*

**Comment by mohitranka** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[gruserver/main_test.go, line 566 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/gru/33#-KNLvo0-vP0YpwYD9BO1:-KNVlv4jNG--m0LoJskl:-499146009) ([raw file](https://github.com/dgraph-io/gru/blob/8325d0e8af7e7d2eacb06a4dcec9ed70d7540074/gruserver/main_test.go#L566)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Good point.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/33)*

**Comment by pawanrawal** [comment]
:lgtm: 

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/33#-:-KNaCE5fCk9adtNWd1vQ:980077423)*

**Comment by mohitranka** [comment]
Merged to develop at commit 00adcd81aa7061735513bb46f33992ccb8d6eba5

**Pull request closed without merging**
