### PR TITLE
Feature/server

### PR DESCRIPTION
**Pull request by pawanrawal**
Made changes according to feedback by Manish.

TODO - Only allow lowercase and - in tags.

---
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/gru/28)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Review status: 0 of 6 files reviewed at latest revision, 3 unresolved discussions.

---

*[server/main.go, line 50 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/28#-KM9EqgZ8-iShIjCpE5c:-KM9EqgZ8-iShIjCpE5d:580854879) ([raw file](https://github.com/dgraph-io/gru/blob/b9c3d9a993f58a0b52edee197cdd035b876b6922/server/main.go#L50)):*
> ```Go
> 	demoDuration   = 10 * time.Minute
> 	quizDuration   = 60 * time.Minute
> 	maxDemoQns     = 8
> ```

This is the number of demo questions asked to dummy candidates.

---

*[server/main.go, line 51 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/28#-KM9Ev5VISVnLm2GFY2_:-KM9Ev5VISVnLm2GFY2a:-1197401381) ([raw file](https://github.com/dgraph-io/gru/blob/b9c3d9a993f58a0b52edee197cdd035b876b6922/server/main.go#L51)):*
> ```Go
> 	quizDuration   = 60 * time.Minute
> 	maxDemoQns     = 8
> 	demoQnsBfrQuiz = 3
> ```

This is the number of demo questions asked to actual test candidates.

---

*[server/main.go, line 575 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/28#-KM9FH20i6WzwE1NHhn5:-KM9FH20i6WzwE1NHhn6:-743927970) ([raw file](https://github.com/dgraph-io/gru/blob/b9c3d9a993f58a0b52edee197cdd035b876b6922/server/main.go#L575)):*
> ```Go
> }
> 
> func (s *server) SendAnswer(ctx context.Context,
> ```

This method doesn't return the score so I am not sure if getScore is a good name for it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/28)*

**Comment by ashwin95r** [comment]
Review status: 0 of 6 files reviewed at latest revision, 5 unresolved discussions.

---

*[server/main.go, line 216 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/28#-KM9LtAxnQUgJ4bylRY-:-KM9LtAxnQUgJ4bylRY0:1174297901) ([raw file](https://github.com/dgraph-io/gru/blob/b9c3d9a993f58a0b52edee197cdd035b876b6922/server/main.go#L216)):*
> ```Go
> }
> 
> func candInfo(token string, c Candidate) (Candidate, error) {
> ```

No need to pass candidate as an argument as it can be read from the cmap using the token.

---

*[server/main.go, line 407 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/28#-KM9MAjqK0oS1qSuD3Dx:-KM9MAjru_CRuzg7DFmM:1998167006) ([raw file](https://github.com/dgraph-io/gru/blob/b9c3d9a993f58a0b52edee197cdd035b876b6922/server/main.go#L407)):*
> ```Go
> }
> 
> func nextQuestion(c Candidate, token string, qnType string) (*interact.Question,
> ```

Same here, candidate info can be obtained from the cmap using token.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/28)*

**Comment by manishrjain** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[server/main.go, line 50 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/28#-KM9EqgZ8-iShIjCpE5c:-KM9GYy2M7L9fr6rf3pM:673865115) ([raw file](https://github.com/dgraph-io/gru/blob/b9c3d9a993f58a0b52edee197cdd035b876b6922/server/main.go#L50)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> This is the number of demo questions asked to dummy candidates.
</details>
This should be a comment.

---

*[server/main.go, line 51 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/28#-KM9Ev5VISVnLm2GFY2_:-KM9GaWTslDpCq7lf1Iy:-535507876) ([raw file](https://github.com/dgraph-io/gru/blob/b9c3d9a993f58a0b52edee197cdd035b876b6922/server/main.go#L51)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> This is the number of demo questions asked to actual test candidates.
</details>
This should also be a comment. Plus, change the variable name, don't remove vowels. `beforeQuiz` or something; so statements would look like if numQuestions < beforeQuiz.. do something.

---

*[server/main.go, line 243 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/28#-KM9JnbLN4SKJ0kyQ_yN:-KM9JnbLN4SKJ0kyQ_yO:-1970712572) ([raw file](https://github.com/dgraph-io/gru/blob/b9c3d9a993f58a0b52edee197cdd035b876b6922/server/main.go#L243)):*
> ```Go
> 	// If we reach here it means logfile for candidate exists but his info
> 	// doesn't exist in memory, so we need to load it back from the file.
> 	err = c.loadCandInfo(token)
> ```

if err := c.loadCandInfo(token); err != nil { return c, err }

---

*[server/main.go, line 332 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/28#-KM9KYMcDUOEfzDmkgje:-KM9KYMcDUOEfzDmkgjf:-11356499) ([raw file](https://github.com/dgraph-io/gru/blob/b9c3d9a993f58a0b52edee197cdd035b876b6922/server/main.go#L332)):*
> ```Go
> 		session = interact.Session{
> 			Id:           RandStringBytes(36),
> 			State:        interact.Quiz_DEMO_NOT_TAKEN,
> ```

Quiz in lowercase, DEMO_NOT_TAKEN in caps. Switch them all to uppercase.

---

*[server/main.go, line 364 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/28#-KM9KpdakzAc_grKE-Zt:-KM9KpdakzAc_grKE-Zu:1109873685) ([raw file](https://github.com/dgraph-io/gru/blob/b9c3d9a993f58a0b52edee197cdd035b876b6922/server/main.go#L364)):*
> ```Go
> 	}
> 
> 	if state(c) == interact.Quiz_DEMO_NOT_TAKEN || state(c) == interact.Quiz_DEMO_STARTED {
> ```

mixed casing here as well

---

*[server/main.go, line 575 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/28#-KM9FH20i6WzwE1NHhn5:-KM9NpwdweLzikA4G0ri:2010251733) ([raw file](https://github.com/dgraph-io/gru/blob/b9c3d9a993f58a0b52edee197cdd035b876b6922/server/main.go#L575)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> This method doesn't return the score so I am not sure if getScore is a good name for it.
</details>
What does it return? Not the actual answer, right?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/28)*

**Comment by pawanrawal** [comment]
Review status: 2 of 6 files reviewed at latest revision, 8 unresolved discussions.

---

*[server/main.go, line 50 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/28#-KM9EqgZ8-iShIjCpE5c:-KMCZyi3_amh1lYepTDG:-499146009) ([raw file](https://github.com/dgraph-io/gru/blob/b9c3d9a993f58a0b52edee197cdd035b876b6922/server/main.go#L50)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> This should be a comment.
</details>
Done.

---

*[server/main.go, line 51 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/28#-KM9Ev5VISVnLm2GFY2_:-KMCZyGOrAOGKjoyLLjd:-499146009) ([raw file](https://github.com/dgraph-io/gru/blob/b9c3d9a993f58a0b52edee197cdd035b876b6922/server/main.go#L51)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> This should also be a comment. Plus, change the variable name, don't remove vowels. `beforeQuiz` or something; so statements would look like if numQuestions < beforeQuiz.. do something.
</details>
Done.

---

*[server/main.go, line 216 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/28#-KM9LtAxnQUgJ4bylRY-:-KMCYi--4e3n7AFXrUGf:-1151758152) ([raw file](https://github.com/dgraph-io/gru/blob/b9c3d9a993f58a0b52edee197cdd035b876b6922/server/main.go#L216)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> No need to pass candidate as an argument as it can be read from the cmap using the token.
</details>
It can be though I'd again wan't to check if the token is valid or not which I have already done in the function which calls this function. Hence this.

---

*[server/main.go, line 243 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/28#-KM9JnbLN4SKJ0kyQ_yN:-KMCbb0qKuk9okwW2zPS:-499146009) ([raw file](https://github.com/dgraph-io/gru/blob/b9c3d9a993f58a0b52edee197cdd035b876b6922/server/main.go#L243)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> if err := c.loadCandInfo(token); err != nil { return c, err }
</details>
Done.

---

*[server/main.go, line 332 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/28#-KM9KYMcDUOEfzDmkgje:-KMCZxS33cxMJJOv5Q3C:-499146009) ([raw file](https://github.com/dgraph-io/gru/blob/b9c3d9a993f58a0b52edee197cdd035b876b6922/server/main.go#L332)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> Quiz in lowercase, DEMO_NOT_TAKEN in caps. Switch them all to uppercase.
</details>
Done.

---

*[server/main.go, line 364 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/28#-KM9KpdakzAc_grKE-Zt:-KMC_-OI96YIRJFe_Kbg:-499146009) ([raw file](https://github.com/dgraph-io/gru/blob/b9c3d9a993f58a0b52edee197cdd035b876b6922/server/main.go#L364)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> mixed casing here as well
</details>
Done.

---

*[server/main.go, line 407 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/28#-KM9MAjqK0oS1qSuD3Dx:-KMC_0aGXRu-RWq4WktW:193739322) ([raw file](https://github.com/dgraph-io/gru/blob/b9c3d9a993f58a0b52edee197cdd035b876b6922/server/main.go#L407)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> Same here, candidate info can be obtained from the cmap using token.
</details>
Same point as above.

---

*[server/main.go, line 575 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/28#-KM9FH20i6WzwE1NHhn5:-KMC_3NXgHtc3pTKgTZa:-326599634) ([raw file](https://github.com/dgraph-io/gru/blob/b9c3d9a993f58a0b52edee197cdd035b876b6922/server/main.go#L575)):*
<details><summary><i>Previously, manishrjain (Manish R Jain) wrote…</i></summary>
> What does it return? Not the actual answer, right?
</details>
Nope just a status.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/28)*

**Comment by manishrjain** [comment]
Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[server/main.go, line 575 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/28#-KM9FH20i6WzwE1NHhn5:-KMDBvolp5KNF-tJEnG_:1352882619) ([raw file](https://github.com/dgraph-io/gru/blob/b9c3d9a993f58a0b52edee197cdd035b876b6922/server/main.go#L575)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Nope just a status.
</details>
Then how about Status()? Btw, what does the status contain?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/28)*

**Comment by manishrjain** [comment]
Change the naming of the SendAnswer, to represent what it actually does. Other than that, LGTM. :lgtm_strong: 

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/28#-:-KMDC7LjO1bnch1bM2df:71053552)*

**Comment by pawanrawal** [comment]
Merged.

**Pull request closed without merging**
