### PR TITLE
Enable context timeout, show unreachable status

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/gru/23)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[client/main.go, line 130 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/23#-KLz21aK7dQUWlGijB_l:-KLz21aK7dQUWlGijB_m:1962385453) ([raw file](https://github.com/dgraph-io/gru/blob/f3be2d55ad399ea32ecc663c7b0305e9a5c85840/client/main.go#L130)):*
> ```Go
> 	}
> 	client := interact.NewGruQuizClient(conn)
> 	ctx, _ := context.WithTimeout(context.Background(), 5*time.Second)
> ```

Maybe keep a count of the number of times you get an error while doing ping in a variable in Session. If that exceeds X , you can show the error page?

---

*[client/render.go, line 167 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/23#-KLz1ICYnXamwuAEESY8:-KLz1ICYnXamwuAEESY9:1553891398) ([raw file](https://github.com/dgraph-io/gru/blob/f3be2d55ad399ea32ecc663c7b0305e9a5c85840/client/render.go#L167)):*
> ```Go
> func statusNoConnection() {
> 	qp.pingbox.Text = "Trouble connecting to the server. Hang on for a sec!"
> 	qp.pingbox.TextFgColor = termui.ColorRed
> ```

Does this work without calling `termui.Render(termui.Body)`

---

*[client/render.go, line 172 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/23#-KLz1WdVHcBdVWcEJvIy:-KLz1WdVHcBdVWcEJvIz:-57160668) ([raw file](https://github.com/dgraph-io/gru/blob/f3be2d55ad399ea32ecc663c7b0305e9a5c85840/client/render.go#L172)):*
> ```Go
> func statusConnected() {
> 	qp.pingbox.Text = "Connected to server"
> 	qp.pingbox.TextFgColor = termui.ColorGreen
> ```

Same as above. Did you test out by bringing server down and back up?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/23)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[client/main.go, line 130 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/23#-KLz21aK7dQUWlGijB_l:-KLz2zwzqzhZ-kR8FIsc:-499146009) ([raw file](https://github.com/dgraph-io/gru/blob/f3be2d55ad399ea32ecc663c7b0305e9a5c85840/client/main.go#L130)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Maybe keep a count of the number of times you get an error while doing ping in a variable in Session. If that exceeds X , you can show the error page?
</details>
Done.

---

*[client/render.go, line 167 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/23#-KLz1ICYnXamwuAEESY8:-KLz2cFNlkxgOly1967E:-1869836824) ([raw file](https://github.com/dgraph-io/gru/blob/f3be2d55ad399ea32ecc663c7b0305e9a5c85840/client/render.go#L167)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Does this work without calling `termui.Render(termui.Body)`
</details>
Yeah it does.

---

*[client/render.go, line 172 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/23#-KLz1WdVHcBdVWcEJvIy:-KLz2eQ1yWr-FWokujZA:677251183) ([raw file](https://github.com/dgraph-io/gru/blob/f3be2d55ad399ea32ecc663c7b0305e9a5c85840/client/render.go#L172)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Same as above. Did you test out by bringing server down and back up?
</details>
Yep.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/23)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[client/main.go, line 130 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/gru/23#-KLz6O68NRcB5JFttmBP:-KLz6O68NRcB5JFttmBQ:1572918185) ([raw file](https://github.com/dgraph-io/gru/blob/e147062fc6cae7753355c42f4a04047a5107a489/client/main.go#L130)):*
> ```Go
> 	}
> 	client := interact.NewGruQuizClient(conn)
> 	ctx, _ := context.WithTimeout(context.Background(), 5*time.Second)
> ```

We already have a constant for PINGDUR, you could reuse that.

---

*[client/main.go, line 136 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/gru/23#-KLz6ST4s-e1sWNnuH6a:-KLz6ST4s-e1sWNnuH6b:-1383880579) ([raw file](https://github.com/dgraph-io/gru/blob/e147062fc6cae7753355c42f4a04047a5107a489/client/main.go#L136)):*
> ```Go
> 		(*pingFail)++
> 		log.Println("While sending ping", err)
> 		if (*pingFail) > 12 {
> ```

This(12) can be also be constant. You use it in all RPC calls.

---

*[client/render.go, line 167 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/23#-KLz1ICYnXamwuAEESY8:-KLz6Y4PXQK2snaQvxxk:-1025700735) ([raw file](https://github.com/dgraph-io/gru/blob/f3be2d55ad399ea32ecc663c7b0305e9a5c85840/client/render.go#L167)):*
<details><summary><i>Previously, ashwin95r (Ashwin Ramesh) wrote…</i></summary>
> Yeah it does.
</details>
Oh, I guess that's because every second it's rendered. Sorry, I forgot.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/23#-:-KLz6dSTc4V3Vc0yX-ND:1417088721)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[client/main.go, line 130 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/gru/23#-KLz6O68NRcB5JFttmBP:-KLzCQDfu2p9VDhLatHM:2088992285) ([raw file](https://github.com/dgraph-io/gru/blob/e147062fc6cae7753355c42f4a04047a5107a489/client/main.go#L130)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> We already have a constant for PINGDUR, you could reuse that.
</details>
Yeah, i'll create another constant as this is not exactly related to PINGDUR.

---

*[client/main.go, line 136 \[r2\]](https://reviewable.io:443/reviews/dgraph-io/gru/23#-KLz6ST4s-e1sWNnuH6a:-KLzCWu5bDsqiv9aS2KM:-718847215) ([raw file](https://github.com/dgraph-io/gru/blob/e147062fc6cae7753355c42f4a04047a5107a489/client/main.go#L136)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> This(12) can be also be constant. You use it in all RPC calls.
</details>
Yeah, I'll name as NUMRETRY

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/23)*

**Comment by ashwin95r** [comment]
Merged.

---

Review status: 1 of 2 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/23#-:-KLzDmoQKtDqkwJ7jQjs:472139197)*

**Pull request closed without merging**
