### PR TITLE
Disallow multiple sessions

### PR DESCRIPTION
**Pull request by ashwin95r**
This change is [Reviewable](https://reviewable.io/reviews/dgraph-io/gru/25)

### CODE REVIEW

**Comment by pawanrawal** [comment]
Review status: 0 of 2 files reviewed at latest revision, 4 unresolved discussions.

---

*[server/main.go, line 280 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/25#-KLzUCs9YBfYRCDihikb:-KLzUCsAHIycscDerT4w:1850919685) ([raw file](https://github.com/dgraph-io/gru/blob/c9faee3d6312626f25e7a5287cfc6a7aa1c40d75/server/main.go#L280)):*
> ```Go
> 		session = interact.Session{Id: RandStringBytes(36), State: interact.Quiz_DEMO_NOT_TAKEN,
> 			TimeLeft:     timeLeft(c.testStart).String(),
> 			TestDuration: DURATION.String()}
> ```

return here and unindent the else block. Btw does it work without a token as it is now? Won't it return `nil,nil`?

---

*[server/main.go, line 290 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/25#-KLzUXkfzKYLQdlr0w7k:-KLzUXkfzKYLQdlr0w7l:-520504238) ([raw file](https://github.com/dgraph-io/gru/blob/c9faee3d6312626f25e7a5287cfc6a7aa1c40d75/server/main.go#L290)):*
> ```Go
> 		}
> 
> 		cand, ok := readMap(t.Id)
> ```

Hmm, we already have the candidate above.

---

*[server/main.go, line 300 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/25#-KLzUiCsYuRc3gkWCwsz:-KLzUiCsYuRc3gkWCwt-:-1901378525) ([raw file](https://github.com/dgraph-io/gru/blob/c9faee3d6312626f25e7a5287cfc6a7aa1c40d75/server/main.go#L300)):*
> ```Go
> 			updateMap(t.Id, c)
> 			return &session, nil
> 		} else {
> ```

You don't need else here, you are returning above.

---

*[server/main.go, line 311 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/25#-KLzUn7byhA4Jx32fEMa:-KLzUn7byhA4Jx32fEMb:50294338) ([raw file](https://github.com/dgraph-io/gru/blob/c9faee3d6312626f25e7a5287cfc6a7aa1c40d75/server/main.go#L311)):*
> ```Go
> 				return &session, nil
> 
> 			} else {
> ```

Else not needed here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/25)*

**Comment by pawanrawal** [comment]
Maybe add some tests for authenticate method.

---

Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/25#-:-KLzZVXHLQdjQofilpO8:-1246996184)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[server/main.go, line 280 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/25#-KLzUCs9YBfYRCDihikb:-KLzZmnaxm_-I1Fmr5eo:-499146009) ([raw file](https://github.com/dgraph-io/gru/blob/c9faee3d6312626f25e7a5287cfc6a7aa1c40d75/server/main.go#L280)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> return here and unindent the else block. Btw does it work without a token as it is now? Won't it return `nil,nil`?
</details>
Done.

---

*[server/main.go, line 290 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/25#-KLzUXkfzKYLQdlr0w7k:-KLzZo2bCeoAXJHLrgsL:-499146009) ([raw file](https://github.com/dgraph-io/gru/blob/c9faee3d6312626f25e7a5287cfc6a7aa1c40d75/server/main.go#L290)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Hmm, we already have the candidate above.
</details>
Done.

---

*[server/main.go, line 300 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/25#-KLzUiCsYuRc3gkWCwsz:-KLzZpLiwkcIRAU3JifH:-499146009) ([raw file](https://github.com/dgraph-io/gru/blob/c9faee3d6312626f25e7a5287cfc6a7aa1c40d75/server/main.go#L300)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> You don't need else here, you are returning above.
</details>
Done.

---

*[server/main.go, line 311 \[r1\]](https://reviewable.io:443/reviews/dgraph-io/gru/25#-KLzUn7byhA4Jx32fEMa:-KLzZq1lhEFU14vQIBcm:-499146009) ([raw file](https://github.com/dgraph-io/gru/blob/c9faee3d6312626f25e7a5287cfc6a7aa1c40d75/server/main.go#L311)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Else not needed here.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/25)*

**Comment by pawanrawal** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[server/main.go, line 276 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/gru/25#-KM-OB90Vjw6eXKbro9v:-KM-OB90Vjw6eXKbro9w:1872127523) ([raw file](https://github.com/dgraph-io/gru/blob/2dce6bd10e29380d8e9808a76d93938595a9321c/server/main.go#L276)):*
> ```Go
> 	var session interact.Session
> 
> 	if strings.HasPrefix(t.Id, "test-") {
> ```

Can you add a test for authenticating test token too?

---

*[server/main.go, line 291 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/gru/25#-KM-MPWz8xsb22XzSWSU:-KM-MPX-SyntAE3u-fmy:596623049) ([raw file](https://github.com/dgraph-io/gru/blob/2dce6bd10e29380d8e9808a76d93938595a9321c/server/main.go#L291)):*
> ```Go
> 	}
> 
> 	timeUntilLastExchange := time.Now().Sub(c.lastExchange)
> ```

timeSinceLastExchange might be better.

---

*[server/main.go, line 292 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/gru/25#-KM-MwfS9sSyTlByq08b:-KM-MwfTrvN8HiUuwtsz:2120231179) ([raw file](https://github.com/dgraph-io/gru/blob/2dce6bd10e29380d8e9808a76d93938595a9321c/server/main.go#L292)):*
> ```Go
> 
> 	timeUntilLastExchange := time.Now().Sub(c.lastExchange)
> 	if c.lastExchange.IsZero() || timeUntilLastExchange > 5*time.Second {
> ```

`if !c.lastExchange.IsZero() && timeSinceLastExchange < 5*time.Second {
// return error
}`
// generate and return session token.

So that larger code block is unindented.

Also our ping duration is 5 second so maybe we could have this as 10 * time. Second, just to be sure that we missed a couple of pings?

---

*[server/main_test.go, line 240 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/gru/25#-KM-O2h_m19zp6jPlHov:-KM-O2h_m19zp6jPlHow:1212010852) ([raw file](https://github.com/dgraph-io/gru/blob/2dce6bd10e29380d8e9808a76d93938595a9321c/server/main_test.go#L240)):*
> ```Go
> 	getQuestion(req)
> 	_, err = authenticate(&token)
> 	if err == nil {
> ```

Check exact error.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/25)*

**Comment by ashwin95r** [comment]
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[server/main.go, line 276 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/gru/25#-KM-OB90Vjw6eXKbro9v:-KM-T8iy1OeimiGejtRF:-499146009) ([raw file](https://github.com/dgraph-io/gru/blob/2dce6bd10e29380d8e9808a76d93938595a9321c/server/main.go#L276)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Can you add a test for authenticating test token too?
</details>
Done.

---

*[server/main.go, line 291 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/gru/25#-KM-MPWz8xsb22XzSWSU:-KM-SqOSUbESv6Wl0Nhd:-499146009) ([raw file](https://github.com/dgraph-io/gru/blob/2dce6bd10e29380d8e9808a76d93938595a9321c/server/main.go#L291)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> timeSinceLastExchange might be better.
</details>
Done.

---

*[server/main.go, line 292 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/gru/25#-KM-MwfS9sSyTlByq08b:-KM-SzAWTTlphUrnPzZJ:398641385) ([raw file](https://github.com/dgraph-io/gru/blob/2dce6bd10e29380d8e9808a76d93938595a9321c/server/main.go#L292)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> `if !c.lastExchange.IsZero() && timeSinceLastExchange < 5*time.Second {
> // return error
> }`
> // generate and return session token.
> 
> So that larger code block is unindented.
> 
> Also our ping duration is 5 second so maybe we could have this as 10 * time. Second, just to be sure that we missed a couple of pings?
</details>
Sure, we could make it 10.

---

*[server/main_test.go, line 240 \[r3\]](https://reviewable.io:443/reviews/dgraph-io/gru/25#-KM-O2h_m19zp6jPlHov:-KM-U5CuVHh_flxIvsIC:-499146009) ([raw file](https://github.com/dgraph-io/gru/blob/2dce6bd10e29380d8e9808a76d93938595a9321c/server/main_test.go#L240)):*
<details><summary><i>Previously, pawanrawal (Pawan Rawal) wrote…</i></summary>
> Check exact error.
</details>
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/25)*

**Comment by pawanrawal** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[server/main_test.go, line 252 \[r4\]](https://reviewable.io:443/reviews/dgraph-io/gru/25#-KM-Xc8SJD-b9FKUBwNO:-KM-Xc8SJD-b9FKUBwNP:636367887) ([raw file](https://github.com/dgraph-io/gru/blob/9284868bc521d5ae930be3dfbbb5e250b95c1968/server/main_test.go#L252)):*
> ```Go
> 	token = interact.Token{Id: "test-abcd"}
> 	_, err = authenticate(&token)
> ```

Also check that you get a valid session id here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/25)*

**Comment by pawanrawal** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/25#-:-KM-Y9VcRT276-tbY-FW:1417088721)*

**Comment by ashwin95r** [comment]
Merged.

---

Review status: 2 of 3 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/dgraph-io/gru/25#-:-KM-c0PPlcblApJmv9D0:472139197)*

**Comment by pawanrawal** [comment]
Merged.

**Pull request closed without merging**
